default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test